import { NextResponse } from 'next/server';

export const maxDuration = 120;

export async function POST(request) {
  try {
    const body = await request.json();
    const { scriptText, transcript, dialogueLines, sfxCues, musicCues, ambientCues, voaCues, audioData } = body;

    if (!scriptText || !transcript) {
      return NextResponse.json({ error: 'Missing script or transcript' }, { status: 400 });
    }

    const groqKey = process.env.GROQ_API_KEY;
    if (!groqKey) {
      return NextResponse.json({ error: 'GROQ_API_KEY not configured.' }, { status: 500 });
    }

    const prompt = `You are an audio QC specialist. You have a SCRIPT and a TRANSCRIPT (auto-generated by Whisper from the recording).

Your job: find ALL problems in the recording by comparing it to the script.

CRITICAL RULES FOR MISSING DIALOGUE:
- Whisper transcription is imperfect. It drops punctuation, changes numbers ("thirty-one hundred" becomes "3100"), changes capitalization, and slightly rewords things. This is NORMAL and must NEVER be flagged.
- A line is MISSING only if its core meaning/words cannot be found ANYWHERE in the transcript.
- If even a rough version of the line exists in the transcript, it is NOT missing.
- Episode titles and headers like "Ep 1" are NOT dialogue — ignore them.
- When in doubt, do NOT flag it. Only flag lines you are highly confident are truly absent.

CRITICAL RULES FOR EXTRA DIALOGUE:
- Check the transcript for any sentences, phrases, or words that are NOT in the original script.
- Extra dialogue includes: ad-libbed lines, repeated lines, wrong lines from another part of the script, the voice actor saying random things (like "take two", "sorry let me redo that", "ok here we go"), or any spoken content that doesn't belong.
- Whisper artifacts like "Thank you for watching", "Subscribe", "Like and share" are NOT real extra dialogue — they are Whisper hallucinations and must be IGNORED.
- Short filler words like "um", "uh", "ah" are normal and should NOT be flagged unless excessive.
- Only flag extra dialogue that is clearly a full phrase or sentence that does not appear anywhere in the script.

SCRIPT:
"""
${scriptText.substring(0, 5500)}
"""

TRANSCRIPT:
"""
${transcript.substring(0, 4500)}
"""

DIALOGUE LINES TO CHECK:
${(dialogueLines || []).slice(0, 60).map((d, i) => (i + 1) + '. ' + d).join('\n')}

AUDIO DATA:
- Duration: ${audioData?.duration || '?'}s
- Long pauses over 3 seconds (MUST be flagged as critical): ${audioData?.longPauses || 'none'}
- All pauses over 0.8s: ${audioData?.allPauses || 'none'}
- Noise spikes / anomalies: ${audioData?.noise || 'none'}

AUDIO DETECTION RULES:
- Every pause longer than 3 seconds MUST be reported as a critical pauseIssue.
- Every noise spike MUST be reported as a noiseIssue.
- Short pauses (0.8-3s) between scenes are normal — only flag as "info" if unusually many.

Respond ONLY with valid JSON (no markdown, no backticks). Keep notes under 15 words. Only report REAL problems:
{
  "overallScore": 0-100,
  "overallVerdict": "PASS|NEEDS_REVIEW|FAIL",
  "summary": "2-3 sentences",
  "missingDialogue": [{"line":"exact missing line from script","severity":"critical|warning","context":"where in script"}],
  "extraDialogue": [{"line":"exact extra words/sentence from transcript","severity":"critical|warning","context":"approximate location in recording"}],
  "mispronunciations": [{"expected":"script word","heard":"transcript word","severity":"warning"}],
  "sfxIssues": [{"cue":"cue","status":"missing|weak","severity":"warning","note":"short"}],
  "musicIssues": [{"cue":"cue","status":"missing|wrong_mood","severity":"warning","note":"short"}],
  "ambientIssues": [{"cue":"cue","status":"missing|weak","severity":"warning","note":"short"}],
  "voiceActingIssues": [{"cue":"cue","status":"not_followed","severity":"warning","note":"short"}],
  "pauseIssues": [{"timestamp":"time","duration":"sec","severity":"critical|info","note":"short"}],
  "noiseIssues": [{"timestamp":"time","severity":"critical|warning","note":"short description"}],
  "additionalNotes": ["short"]
}`;

    const resp = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + groqKey,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: 'You are a strict audio QC tool. Report lines TRULY ABSENT from transcript, and lines in the transcript that are NOT in the script (extra/ad-libbed dialogue). Ignore Whisper artifacts like "thank you for watching" or "subscribe". Flag every long pause (>3s) and noise spike. Return valid JSON only.' },
          { role: 'user', content: prompt }
        ],
        max_tokens: 4096,
        temperature: 0,
      }),
    });

    if (!resp.ok) {
      const errText = await resp.text();
      let errMsg;
      try { errMsg = JSON.parse(errText).error?.message; } catch (e) { errMsg = errText.substring(0, 200); }
      return NextResponse.json({ error: errMsg || 'Analysis failed (' + resp.status + ')' }, { status: resp.status });
    }

    const data = await resp.json();
    const text = (data.choices?.[0]?.message?.content || '').trim();
    let clean = text.replace(/```json|```/g, '').trim();

    let parsed;
    try {
      parsed = JSON.parse(clean);
    } catch (e) {
      let s = clean;
      if ((s.match(/"/g) || []).length % 2 !== 0) s += '"';
      const opens = { '[': 0, '{': 0 };
      for (const ch of s) { if (ch === '[' || ch === '{') opens[ch]++; if (ch === ']') opens['[']--; if (ch === '}') opens['{']--; }
      for (let i = 0; i < opens['[']; i++) s += ']';
      for (let i = 0; i < opens['{']; i++) s += '}';
      s = s.replace(/,\s*([}\]])/g, '$1');
      try { parsed = JSON.parse(s); } catch (e2) {
        return NextResponse.json({ error: 'Could not parse AI response. Try again.' }, { status: 500 });
      }
    }

    return NextResponse.json(parsed);
  } catch (err) {
    console.error('Analyze error:', err);
    return NextResponse.json({ error: 'Server error: ' + err.message }, { status: 500 });
  }
}
