import { NextResponse } from 'next/server';

export const maxDuration = 120;

export async function POST(request) {
  try {
    const body = await request.json();
    const { scriptText, transcript, dialogueLines, sfxCues, musicCues, ambientCues, voaCues, audioData } = body;

    if (!scriptText || !transcript) {
      return NextResponse.json({ error: 'Missing script or transcript' }, { status: 400 });
    }

    const groqKey = process.env.GROQ_API_KEY;
    if (!groqKey) {
      return NextResponse.json({ error: 'GROQ_API_KEY not configured.' }, { status: 500 });
    }

    const prompt = `You are an audio QC specialist. You have a SCRIPT and a TRANSCRIPT (auto-generated by Whisper from the recording).

Your job: find lines from the script that are TRULY MISSING from the transcript.

CRITICAL RULES:
- Whisper transcription is imperfect. It drops punctuation, changes numbers (e.g. "thirty-one hundred" becomes "3100"), changes capitalization, and slightly rewords things. This is NORMAL and must NEVER be flagged.
- A line is MISSING only if its core meaning/words cannot be found ANYWHERE in the transcript.
- If even a rough version of the line exists in the transcript, it is NOT missing.
- Episode titles, headers like "Ep 1" are NOT dialogue — ignore them completely.
- When in doubt, do NOT flag it. Only flag lines you are highly confident are truly absent.
- Most recordings follow the script closely. Expect very FEW missing lines, not many.

SCRIPT:
"""
${scriptText.substring(0, 5500)}
"""

TRANSCRIPT:
"""
${transcript.substring(0, 4500)}
"""

DIALOGUE LINES TO CHECK:
${(dialogueLines || []).slice(0, 60).map((d, i) => (i + 1) + '. ' + d).join('\n')}

AUDIO: Duration ${audioData?.duration || '?'}s | ${audioData?.pauseCount || 0} pauses | ${audioData?.noiseCount || 0} noise spikes

Respond ONLY with valid JSON (no markdown, no backticks). Keep notes under 15 words. Only report REAL problems:
{
  "overallScore": 0-100,
  "overallVerdict": "PASS|NEEDS_REVIEW|FAIL",
  "summary": "2-3 sentences",
  "missingDialogue": [{"line":"exact missing line","severity":"critical|warning","context":"where in script"}],
  "mispronunciations": [{"expected":"script word","heard":"transcript word","severity":"warning"}],
  "sfxIssues": [{"cue":"cue","status":"missing|weak","severity":"warning","note":"short"}],
  "musicIssues": [{"cue":"cue","status":"missing|wrong_mood","severity":"warning","note":"short"}],
  "ambientIssues": [{"cue":"cue","status":"missing|weak","severity":"warning","note":"short"}],
  "voiceActingIssues": [{"cue":"cue","status":"not_followed","severity":"warning","note":"short"}],
  "pauseIssues": [{"timestamp":"time","duration":"sec","severity":"info","note":"short"}],
  "noiseIssues": [{"timestamp":"time","severity":"warning","note":"short"}],
  "additionalNotes": ["short"]
}`;

    const resp = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + groqKey,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: 'You are a strict QC tool. Only report lines that are TRULY ABSENT from the transcript. Whisper transcription errors (punctuation, numbers, minor rewording) are NOT problems. When unsure, mark it as present. Return valid JSON only.' },
          { role: 'user', content: prompt }
        ],
        max_tokens: 4096,
        temperature: 0,
      }),
    });

    if (!resp.ok) {
      const errText = await resp.text();
      let errMsg;
      try { errMsg = JSON.parse(errText).error?.message; } catch (e) { errMsg = errText.substring(0, 200); }
      return NextResponse.json({ error: errMsg || 'Analysis failed (' + resp.status + ')' }, { status: resp.status });
    }

    const data = await resp.json();
    const text = (data.choices?.[0]?.message?.content || '').trim();
    let clean = text.replace(/```json|```/g, '').trim();

    let parsed;
    try {
      parsed = JSON.parse(clean);
    } catch (e) {
      let s = clean;
      if ((s.match(/"/g) || []).length % 2 !== 0) s += '"';
      const opens = { '[': 0, '{': 0 };
      for (const ch of s) { if (ch === '[' || ch === '{') opens[ch]++; if (ch === ']') opens['[']--; if (ch === '}') opens['{']--; }
      for (let i = 0; i < opens['[']; i++) s += ']';
      for (let i = 0; i < opens['{']; i++) s += '}';
      s = s.replace(/,\s*([}\]])/g, '$1');
      try { parsed = JSON.parse(s); } catch (e2) {
        return NextResponse.json({ error: 'Could not parse AI response. Try again.' }, { status: 500 });
      }
    }

    return NextResponse.json(parsed);
  } catch (err) {
    console.error('Analyze error:', err);
    return NextResponse.json({ error: 'Server error: ' + err.message }, { status: 500 });
  }
}
